### ISSUE TITLE
Bug on .opacity

### ISSUE THREAD

**Issue by zreedeecom** [mdo/preboot#10]
You have made a mistake here:

// Opacity
.opacity(@opacity: 100) {
    filter: e(%("alpha(opacity=%d)", @opacity));
    -khtml-opacity: @op / 100;
    -moz-opacity: @op / 100;
    opacity: @op / 100;
}

you have used @op instead of @opacity and this throws an error.

Cheers.

**Comment by zreedeecom** [comment]
Also you can add support for IE8:

-ms-filter:"progid:DXImageTransform.Microsoft.Alpha(Opacity=50)";

**Comment by erikzaadi** [comment]
Fixed in pull request 12 (https://github.com/markdotto/Bootstrap.less/pull/12)

**Comment by zreedeecom** [comment]
@erikzaadi cool! I have a question though.. I can I make a pull request? do you know where is this documented?

**Comment by erikzaadi** [comment]
@zreedeecom Sure, basically you fork the desired repository to your account (http://help.github.com/fork-a-repo/), make your changes and press the pull request button (http://help.github.com/send-pull-requests/).

Hope this helps.

**Comment by zreedeecom** [comment]
Thanks! didn't know it was so easy.

**Comment by iamkyle** [comment]
ha, whoops.. guess i should have checked the issues before fixing it on my own :)

**Comment by zreedeecom** [comment]
hehe

**Comment by soniktrooth** [comment]
This bug still exists. Any chance it's going to get rolled in?

**Comment by mdo** [comment]
Punting this and all other issues against master ahead of v2 release. No longer applicable. Thanks though!
