### ISSUE TITLE
sans-serif declaration in serif font stack

### ISSUE THREAD

**Issue by aripalo** [mdo/preboot#19]
In font stack declarations there's a small, but meaningful mistake: In serif font stack after Georgia, Times New Roman and Times the last fallback font-family is "sans-serif" instead of "serif". 

.serif(@weight: normal, @size: 14px, @lineHeight: 20px) {
    font-family: "Georgia", Times New Roman, Times, sans-serif;
    font-size: @size;
    font-weight: @weight;
    line-height: @lineHeight;
  }

**Comment by mdo** [comment]
Punting this and all other issues against master ahead of v2 release.

We nuked all the font mixins—they were too verbose and not very helpful. Thanks though!
