### ISSUE TITLE
.border-radius mixin is redundant

### ISSUE THREAD

**Issue by ubuwaits** [mdo/preboot#2]
The .border-radius is redundant because all of that functionality is available through the .rounded mixin. The native border-radius CSS property supports this shorthand notation:

border-radius: topleft topright bottomright bottomleft;

You can just send the .rounded mixin one string with all these values.

**Comment by mdo** [comment]
Yes, they are redundant—got stuck thinking I needed to support the old -webkit-border-radius syntax (which didn't allow all four properties in shorthand form). Since Safari 5 does support border-radius now, I'll consolidate the two in the next push.

Thanks!
