### ISSUE TITLE
Button background-color

### ISSUE THREAD

**Issue by adtaylor** [mdo/preboot#3]
Hi,

I was having a problem with the background colours of the buttons (ie **a.button.purple**)  being overriden by the default gradient colour. I found that removing lines 117 & 118 helped solve this for me:

```
#gradient > .vertical(
   );
```

Thanks for putting this together, I can see this fitting in brilliantly with HTML5 Boilerplate.

Cheers,
Ad

**Comment by mdo** [comment]
Sorry about that—just pushed a fix to resolve this. Thanks!
