### ISSUE TITLE
Missing .border-radius() mixin.

### ISSUE THREAD

**Issue by soniktrooth** [mdo/preboot#38]
.border-radius() was in v1 but seems to have been removed in favour of the more verbose single side mixins. Seems like an obvious use case—am I missing something or was this overlooked?

**Comment by soniktrooth** [comment]
Silly me, nm

**Comment by pudgereyem** [comment]
What do you mean @soniktrooth? Why are you feeling silly? I also miss the .border-radius mixin.

**Comment by soniktrooth** [comment]
Because border-radius is unprefixed in all modern browsers now. The only reason there was a mixin for it was to add all the -webkit, -moz, -o, -ms prefixes to it.
