### ISSUE TITLE
Preboot variables

### ISSUE THREAD

**Issue by pudgereyem** [mdo/preboot#39]
When building a website based upon preboot, you sometimes want to add some mixins or what not from Bootstrap. But the variable names are not the same for preboot and bootstrap.

For example, Preboot uses _@line-height-base_ when Bootstrap uses _@baseLineHeight_. 
Question is, why?

**Comment by mdo** [comment]
The variables in Bootstrap will change to match in v3.

**Comment by pudgereyem** [comment]
Okay, cool.. When are you planning on releasing v3?
